### ISSUE TITLE
Mode 7 Demo

### ISSUE THREAD

**Issue by 4k3or3et** [CookiePLMonster/flipper-bakery#4]
Hi Sir,

Kindly please put Mode 7 Demo app on flipper store. This is ultra cool app.

**Comment by CookiePLMonster** [comment]
In its current state it's just not enough to be on the app store - but at some point in the near future I'll get CI running on this repository again (need to figure out how to make it run for multiple apps), and I'll again be offering a precompiled FAP here.

**Comment by 4k3or3et** [comment]
Hi there,

any luck with the FAP file? So eager to run it on my flipper... :-)

**Comment by CookiePLMonster** [comment]
Builds are now back!
https://github.com/CookiePLMonster/flipper-bakery/releases/tag/version-1

Do note - the demo is completely untested, it may or may not work. If it crashes or freezes, please reopen this ticket or create a new one.
